[tool.poetry]
name = "paranoid-archive"
version = "0.1.0"
description = ""
authors = ["Yucheng Huang <yu.huang@f5.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
